# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rejectable',
            fields=[
                ('what', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('toWhom', models.CharField(max_length=200)),
                ('accepted', models.BooleanField(default=False)),
                ('isPending', models.BooleanField(default=True)),
                ('when', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
